## Tarea S9.01. Creación de funciones, estructuras de datos y bucles

### *Andrey Ismagilov*
### *Fecha 19/12/2025*

##### **Nivel 1**

Importamos las librerias.

In [242]:
import numpy as np
from numpy import random
from random import sample
import pyperclip
import re
import statistics as st
import pandas as pd

#### 1. Calculadora del índice de masa corporal

- Escribe una función que calcule el IMC ingresado por el usuario/a, es decir, quien lo ejecute deberá ingresar estos datos. Puedes obtener más información de su cálculo en: 🔗 Índice de masa corporal IMC que es y cómo se calcula.

- La función debe clasificar el resultado en sus respectivas categorías.

Consejo: Intenta validar los datos previamente, para que envíe un mensaje de advertencia si los datos introducidos por el usuario/a no están en el formato adecuado o no toma valores razonables.

In [ ]:

def inputNumValidado(prompt_num):
    # Función para validar el parametro introducido
    # Recibe como el argumento "prompt_num" de tipo string.
    # Devuelve el número introducido en caso si la validacion sea exitosa o "-1" en caso contrario.
    try:
        num = float(input(prompt_num))
    except ValueError :
        print("Error: el parametro debe ser numero entero o decimal")
        return -1
    if num <= 0:
        print("Error: el parametro debe ser más de zero")
        return -1
    return num

def clasificarPeso(peso, altura):
    # Función para calcular IMC y clasificar el peso
    imc = round(peso/altura**2, 1)
    if imc < 18.5:
        rango = "peso bajo"
    elif imc < 25:
        rango = "peso normal"
    elif imc < 30:
        rango = "sobrepeso"
    else:
        rango = "obesidad"
    return imc, rango

In [13]:
def main_imc():
    print("""    ***********************************************
    *** Calculadora del índice de masa corporal ***
    ***********************************************""")
    tu_peso = -1
    tu_altura = -1
    while tu_peso == -1:
        tu_peso = inputNumValidado("Tu peso en kilos:")
    while tu_altura == -1:
        tu_altura = inputNumValidado("Tu altura en metros:")
    tuIMC, tuRango = clasificarPeso(tu_peso, tu_altura)

    print(f"Tu peso: {tu_peso} kg, Tu altura: {tu_altura} metros")
    print(f"Tu IMC: {tuIMC}. Tienes {tuRango}")

In [14]:
main_imc()

    ***********************************************
    *** Calculadora del índice de masa corporal ***
    ***********************************************
Tu peso: 70.0 kg, Tu altura: 1.75 metros
Tu IMC: 22.9. Tienes peso normal

2. Conversor de temperaturas

Existen diversas unidades de temperatura utilizadas en distintos contextos y regiones. Las más comunes son Celsius (°C), Fahrenheit (°F) y Kelvin (K). También existen otras unidades como Rankine (°Ra) y Réaumur (°Re).

Selecciona al menos 2 conversores, de modo que al introducir una temperatura devuelva, como mínimo, dos conversiones, de modo que se puedan guardar (recuerda que un print() no se puede guardar nunca).

Consejo: Intenta validar los datos previamente, para que envíe un mensaje de advertencia si los datos introducidos por el usuario/a no están en el formato adecuado.

(EXTRA): Piensa una manera de almacenar todas las posibles conversiones en un solo objeto (¿Lista? ¿Diccionario? ¿DataFrame?) en vez de escribir muchos if else en función de la temperatura de origen y la temperatura de destino.

In [ ]:
def validarTemperatura(prompt_temp):
    es_temperatura_string = True
    while es_temperatura_string:
        try:
            temperatura = float(input(prompt_temp))
            es_temperatura_string = False
            return temperatura
        except:
            print("Error: el parametro debe ser en numero entero o decimal")
    

def validarUnidad(prompt_unidad):
    es_unidad_no_correcta = True
    unidad_opcion = ["celsius", "fahrenheit", "kelvin", "rankine", "reaumur"]
    while  es_unidad_no_correcta:
        unidad = input(prompt_unidad)
        if unidad in unidad_opcion:
            es_unidad_no_correcta = False
        else:
            print("Error: unidad debe ser ", unidad_opcion)    
    return unidad


def conversor_a_celsius(t, u):
    A_CELSIUS = {
        "celsius": lambda t: t,
        "fahrenheit": lambda t: round((t - 32) / 1.8, 2),
        "kelvin": lambda t: t - 273.15,
        "rankine": lambda t: round((t - 491.67) / 1.8, 2),
        "reaumur": lambda t: round(t / 0.8, 2)
                }
    return A_CELSIUS[u](t)

def conversor_desde_celsius(t, u):
    DESDE_CELSIUS = {
        "celsius": lambda t: t,
        "fahrenheit": lambda t: t * 1.8 + 32,
        "kelvin": lambda t: t + 273.15,
        "rankine": lambda t: (t + 273.15) * 1.8,
        "reaumur": lambda t: t * 0.8 
        }
    return DESDE_CELSIUS[u](t)

def conversor_a_fahrenheit(t, u):
    A_FAHRENHEIT = {
        "celsius": lambda t: round(t*1.8 + 32, 2),
        "fahrenheit": lambda t: t,
        "kelvin": lambda t: round(t * 1.8 - 459.67,2),
        "rankine": lambda t: round(t - 459.67, 2),
        "reaumur": lambda t: round(t * 2.25 + 32, 2)
    }
    return A_FAHRENHEIT[u](t)

def conversor_desde_fahrenheit(t, u):
    DESDE_FAHRENHEIT = {
        "celsius": lambda t: round((t - 32)/1.8, 2),
        "fahrenheit": lambda t: t,
        "kelvin": lambda t: round((t + 459.67)/1.8, 2),
        "rankine": lambda t: round(t + 459.67, 2),
        "reaumur": lambda t: round((t - 32)/2.25, 2)
    }
    return DESDE_FAHRENHEIT[u](t)

In [127]:
def executar_conversion():
    my_temperatura = validarTemperatura("Temperatura:")
    my_unidad = validarUnidad("Unidad de temperatura: celsius, fahrenheit, kelvin, rankine, reaumur")

    resultado1 = conversor_a_celsius(my_temperatura, my_unidad)
    print(f"{my_temperatura} {my_unidad} = {resultado1} celsius")

    resultado2 = conversor_desde_celsius(my_temperatura, my_unidad)
    print(f"{my_temperatura} celsius = {resultado2} {my_unidad}")

    resultado3 = conversor_a_fahrenheit(my_temperatura, my_unidad)
    print(f"{my_temperatura} {my_unidad} = {resultado3} fahrenheit")

    resultado4 = conversor_desde_fahrenheit(my_temperatura, my_unidad)
    print(f"{my_temperatura} fahrenheit = {resultado4} {my_unidad}")

In [129]:
executar_conversion()

0.0 kelvin = -273.15 celsius
0.0 celsius = 273.15 kelvin
0.0 kelvin = -459.67 fahrenheit
0.0 fahrenheit = 255.37 kelvin

3. Contador de palabras de un texto.

Escribe una función que dado un texto, muestre las veces que aparece cada palabra. Intenta que se gestionen todas las posibles casuísticas que hagan que el programa no funcione correctamente.

(EXTRA): ¿Cuál es la longitud media de las palabras del texto que has escrito? “¿Hola cómo va?” debería devolver (4+3+2) / 3 = 3m

In [153]:
def frase_a_diccionario(frase):

    lista = re.findall(r'\b\w+\b', frase.lower())

    diccionario = {}
    for palabra in lista:
        palabra_esta_en_diccionario = False
        # Comprobamos si la palabra de la lista hay en diccionario
        for k in diccionario.keys():
            if palabra == k:
                palabra_esta_en_diccionario = True
                break
        # Si no hay contamos cuantos veces se aparece en la lista     
        if palabra_esta_en_diccionario:
            continue
        else:
            counter = lista.count(palabra)
            diccionario[palabra] = counter
    diccionario_sorted = dict( sorted(diccionario.items(), key=lambda item: item[0]) )
    return(diccionario_sorted)

def obtenerMediaLongitudDePalabra(my_dict):
    if len(my_dict) == 0: 
        return 0
    else: 
        return round(st.mean(map(len, my_dict)), 0)

In [198]:
def contador_de_palabras():
    # mi_frase = "En la casa de Pinocho todos cuentan hasta Ocho: Pin uno, piN dos, pin cuatro, pin cinco, pin seis, pin siete, pin ocho."
    mi_frase = input("Escribe una frase:")
    mi_dict = frase_a_diccionario(mi_frase)
    print(mi_dict)
    print(obtenerMediaLongitudDePalabra(mi_dict))

In [199]:
contador_de_palabras()

{'casa': 1, 'cinco': 1, 'cuatro': 1, 'cuentan': 1, 'de': 1, 'dos': 1, 'en': 1, 'hasta': 1, 'la': 1, 'ocho': 2, 'pin': 7, 'pinocho': 1, 'seis': 1, 'siete': 1, 'todos': 1, 'uno': 1}
4.0

4. Diccionario inverso (con posibilidad de duplicados)

Resulta que el cliente tiene una encuesta muy antigua que se almacena en un diccionario y los resultados los necesita a la inversa, es decir, intercambiando las claves y valores. Los valores y claves en el diccionario original son únicos; si éste no es el caso, la función debería imprimir un mensaje de advertencia, junto con una lista con los valores asociados a la clave repetida.

Fíjate en los siguientes ejemplos para ver el output esperado.

In [194]:
def reverse_dictionary(my_dict):
    new_dict = {}
    new_dict_tiene_valores_repetidos = False
    for k, v in my_dict.items():
        # Comprobamos si el diccionario tiene valores de tipo list, tuple, dict, set.
        if isinstance(v, (list, tuple, dict, set)):
            print("Error: no se puede crear el diccionario inverso. El diccionario recibido tiene valores de tipo colecciones de datos.")
            return
        new_dict_key = new_dict.get(v)
        if new_dict_key == None:
            new_dict[v] = k
        else:
            new_dict_tiene_valores_repetidos = True
            if isinstance(new_dict_key, list):
                new_dict[v].append(k)
            else:
                new_dict[v] = [new_dict_key, k]
    if new_dict_tiene_valores_repetidos == True: 
        print("Advertencia: diccionario tiene valores con claves repetidos")
    return(new_dict)

In [195]:
def main_diccionarios_inversos():
    my_dict1 = {'a':1, 'b':2, 'c':3}
    print(my_dict1)
    my_dict_revers1 = reverse_dictionary(my_dict1)
    print(my_dict_revers1)
    print("***************************************************************************************************")
    my_dict2 = {'a':1, 'b':2, 'c':3, 'd':('s', 'g')}
    print(my_dict2)
    my_dict_revers2= reverse_dictionary(my_dict2)
    print(my_dict_revers2)
    print("***************************************************************************************************")
    my_dict3 = {'x':'apple', 'y':'banana', 'z':'banana', 'w': 'banana', 'q':'cereza'}
    print(my_dict3)
    my_dict_revers3 = reverse_dictionary(my_dict3)
    print(my_dict_revers3)

In [196]:
main_diccionarios_inversos()

{'a': 1, 'b': 2, 'c': 3}
{1: 'a', 2: 'b', 3: 'c'}
***************************************************************************************************
{'a': 1, 'b': 2, 'c': 3, 'd': ('s', 'g')}
Error: no se puede crear el diccionario inverso. El diccionario recibido tiene valores de tipo colecciones de datos.
None
***************************************************************************************************
{'x': 'apple', 'y': 'banana', 'z': 'banana', 'w': 'banana', 'q': 'cereza'}
Advertencia: diccionario tiene valores con claves repetidos
{'apple': 'x', 'banana': ['y', 'z', 'w'], 'cereza': 'q'}

##### **Nivel 2**

1. Contador y ordenador de palabras de un texto.

El cliente quedó contento con el contador de palabras, pero ahora quiere leer archivos TXT y que calcule la frecuencia de cada palabra ordenadas dentro de las entradas habituales del diccionario según la letra con la que comienzan, es decir, las claves deben ir de la A a la Z y dentro de la A debemos ir de la A a Z. "tu_me_quieres_blanca.txt" la salida esperada sería:

In [208]:

def dict_a_dict_con_subdict(my_dict):
    # Función recibe como el argumento diccionario con palabras y número de veces que aparece la palabra
    # y devuelva el diccionario con subdiccionarios donde la clave de cada subdiccionario sea la letra alfabetica
    # con que comienza cada palabra del subdiccionario.
    primera_letra = list(my_dict.keys())[0][0]
    dict_with_subdict = { primera_letra: {} }
    for k, v in my_dict.items():
        if k[0] == primera_letra:
            dict_with_subdict[primera_letra][k] = v
        else:
            primera_letra = k[0]
            dict_with_subdict.update({k[0]: {k: v}})
    return(dict_with_subdict)

In [209]:
def contar_ordenar_palabras():
    f = open("tu me quieres blanca.txt", encoding='utf-8')
    my_frase = f.read()
    f.close()
    # Usamos la función "frase_a_diccionario" del ejercicio 3 de nivel 1
    my_dict = dict_a_dict_con_subdict(frase_a_diccionario(my_frase))
    print(my_dict)

In [210]:
contar_ordenar_palabras()

{'a': {'a': 3, 'agua': 1, 'al': 2, 'alba': 4, 'alcobas': 1, 'alimenta': 1, 'alma': 1, 'amarga': 1, 'azucena': 1}, 'b': {'baco': 1, 'banquete': 1, 'bebe': 1, 'blanca': 3, 'boca': 1, 'bosques': 1, 'buen': 1}, 'c': {'cabañas': 1, 'carnes': 2, 'casta': 3, 'cerrada': 1, 'con': 4, 'conservas': 1, 'copas': 1, 'corola': 1, 'corriste': 1, 'cuando': 2, 'cubierto': 1, 'cuerpo': 1, 'cuáles': 1}, 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1}, 'e': {'el': 4, 'ellas': 1, 'en': 4, 'engaño': 1, 'enredada': 1, 'entonces': 1, 'escarcha': 1, 'espumas': 1, 'esqueleto': 1, 'estrago': 1}, 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1}, 'h': {'habla': 1, 'hacia': 1, 'haya': 1, 'hayas': 1, 'hermana': 1, 'hombre': 1, 'hubiste': 1, 'huye': 1}, 'i': {'intacto': 1}, 'j': {'jardines': 1}, 'l': {'la': 3, 'labios': 1, 'las': 7, 'lo': 2, 'los': 4, 'luna': 1, 'lévate': 1, 'límpiate': 1}, 'm': {'mano': 1, 'manos': 1, 'margarita': 1, 'me': 10, 'mi': 1, 'mieles': 1, 'milagros': 1, 'mojada': 1, 'montaña': 1, 'morados': 1}, 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2}, 'p': {'perdone': 2, 'perfume': 1, 'por': 2, 'pretendes': 3, 'preténdeme': 3, 'puesto': 1, 'pájaros': 1, 'pámpanos': 1}, 'q': {'que': 6, 'quedó': 1, 'quieres': 6}, 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1}, 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1}, 't': {'te': 3, 'tejidos': 1, 'tenue': 1, 'tierra': 1, 'toca': 1, 'todas': 2, 'todavía': 1, 'tornadas': 1, 'tú': 8}, 'u': {'un': 1, 'una': 1}, 'v': {'vestido': 1, 'vete': 1, 'vive': 1}, 'y': {'y': 5}}

2. Conversión de tipos de datos.

El cliente recibe una lista de datos y necesita generar dos listas, la primera donde estarán todos los elementos que pudieron convertirse en flotantes y la otra donde están los elementos que no pudieron convertirse.

Opcion 1:

In [215]:
def conversor_de_lista(my_list):
    # Función recibe como el argumento lista y devuelva tres listas:
    # la primera: la lista de números decimales
    # la segunda: la lista de otras elementos
    # la tercera: la lista de elementos de tipo dict y subelementos de tipo dict, list, set, tuple
    lista_de_numeros = []
    lista_de_otras = []
    lista_de_dict = []
    for elem in my_list:
        if isinstance(elem, (list, tuple, set)):
            nums, otras, dicts = conversor_de_lista(elem)
            lista_de_numeros.extend(nums)
            lista_de_otras.extend(otras)
            lista_de_dict.extend(dicts)

        elif isinstance(elem, dict):
            lista_de_dict.append(elem)
        
        else:
            try:
                lista_de_numeros.append(float(elem))
            except (ValueError, TypeError):
                lista_de_otras.append(elem)
       
    return lista_de_numeros, lista_de_otras,  lista_de_dict

In [230]:
def main_conversor_de_datos():
    lista_de_datos = ['1.3', 'one', '1e10', 'seven', '3-1/2', ('2',1,1.4,'not-a-number'), [1,2,3,'3.4', (5.16, '5-16', [517, 518, "a519"])], 2.4, {4 : 1, 'b':2, 'c':3}]
    lista1, lista2, lista3 = conversor_de_lista(lista_de_datos)
    print(lista1)
    print(lista2)
    print(lista3)

In [229]:
main_conversor_de_datos()

[1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4, 5.16, 517.0, 518.0, 519.0, 2.4]
['one', 'seven', '3-1/2', 'not-a-number', '5-16']
[{4: 1, 'b': 2, 'c': 3}]

Opcion 2.

In [231]:
def conversor_de_lista_option_2(my_list): 
    lista_temp = []
    lista_de_numeros = []
    lista_de_otras = []
    lista_de_dict = []
    # Separamos los elementos de tipo dict y agregamoslos en la lista de diccionarios
    for elem in my_list:
        if isinstance(elem, dict):
            lista_de_dict.append(elem)
        else:
            lista_temp.append(elem)
    # Convertimos la lista temporaria a string y eliminamos los caracteres innecesarios.
    my_str = str(lista_temp).replace(",", " ") \
                            .replace("(", " ") \
                            .replace(")", " ") \
                            .replace("[", " ") \
                            .replace("]", " ") \
                            .replace("'", " ")
    my_list_temp = my_str.split()
    for elem in my_list_temp:
        if isinstance(elem, (int, float, complex) ):
            lista_de_numeros.append(float(elem))
        if isinstance(elem, str):
            try:
                lista_de_numeros.append(float(elem))
            except:
                lista_de_otras.append(elem)
    return(lista_de_numeros, lista_de_otras,  lista_de_dict)

In [232]:
def main_conversor_de_datos_option2():
    lista_de_datos = ['1.3', 'one', '1e10', 'seven', '3-1/2', ('2',1,1.4,'not-a-number'), [1,2,3,'3.4', (5.16, '5-16', [517, 518, "a519"])], 2.4, {4 : 1, 'b':2, 'c':3}]
    lista1, lista2, lista3 = conversor_de_lista_option_2(lista_de_datos)
    print(lista1)
    print(lista2)
    print(lista3)

In [233]:
main_conversor_de_datos_option2()

[1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4, 5.16, 517.0, 518.0, 2.4]
['one', 'seven', '3-1/2', 'not-a-number', '5-16', 'a519']
[{4: 1, 'b': 2, 'c': 3}]

##### **Nivel 3**

1. Generador de Contraseñas

Explora el funcionamiento del módulo random de la librería numpy. 🔗 Random module in NumPy

En este punto, el cliente ha detectado un problema con las contraseñas que utilizan sus trabajadores. Asdf1234, fechas de cumpleaños o similares. Para solucionarlo, nos ha encargado una función de Python que genere contraseñas más seguras. La función debe depender de los siguientes parámetros:

- longitud (int): Longitud de la contraseña
- mayúsculas (bool = True): Si tiene que aparecer mayúsculas
- minúsculas (bool = True): Si tiene que aparecer minúsculas
- números (bool = True): Si tiene que aparecer números
- signos (bool = False): Si tiene que aparecer caracteres especiales (,-$? o similares)

Así pues, si ejecutamos la función de la siguiente forma:

crear_contraseña(10, True, True, True, True)

Deberíamos obtener un output (que debemos poder guardar) del estilo:

9Er,5Vn8P$

Asegúrate de que se cumplan todos los criterios, y que estas contraseñas sean realmente aleatorias.

(EXTRA) Explora cómo podríamos hacer que la función copiara la contraseña automáticamente en el portapapeles del ordenador (como si la hubiéramos seleccionado y hecho ctrl+copy).

In [235]:
def crear_contraseña(longitud_contr, hay_mayusculas, hay_minuskulas, hay_numeros, hay_symb_especiales):
    symb_mayusculas = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    symb_minusculas = 'abcdefghijklmnopqrstuvwxyz'
    numeros = '0123456789'
    symb_especiales = '!"#$%&*+,-./:;?@^_'

    symb_para_generar_contraseña = ""
    parte_obligatoria = []
    longitud_maxima = len(symb_mayusculas + symb_minusculas + numeros + symb_especiales)

    if longitud_contr < 4:
        print("Longitud minima de contraseña debe ser 4 characteres.")
        return
    if not (hay_mayusculas + hay_minuskulas + hay_numeros + hay_symb_especiales):
        print("No se puede generar contraseña.")
        return
    if longitud_contr > longitud_maxima:
        print(f"Longitud maxima de contraseña debe ser menos de {longitud_maxima}.")
        return
    
    if hay_mayusculas: 
        symb_para_generar_contraseña = symb_para_generar_contraseña + symb_mayusculas
        parte_obligatoria.append( symb_mayusculas[np.random.randint(len(symb_mayusculas))] )
    if hay_minuskulas: 
        symb_para_generar_contraseña = symb_para_generar_contraseña + symb_minusculas
        parte_obligatoria.append( symb_minusculas[np.random.randint(len(symb_minusculas))] )
    if hay_numeros:
        symb_para_generar_contraseña = symb_para_generar_contraseña + numeros
        parte_obligatoria.append( numeros[np.random.randint(len(numeros))] )
    if hay_symb_especiales:
        symb_para_generar_contraseña = symb_para_generar_contraseña + symb_especiales
        parte_obligatoria.append( symb_especiales[np.random.randint(len(symb_especiales))] )
    list_symb = list(symb_para_generar_contraseña)
    resto_de_contraseña_lista = sample(list_symb, longitud_contr - len(parte_obligatoria))
    contraseña = parte_obligatoria + resto_de_contraseña_lista
    contraseña_array = np.asarray(contraseña)
    random.shuffle(contraseña_array)
    return("".join(str(x) for x in contraseña_array))

In [236]:
def main_crear_contraseña():
    contraseña = crear_contraseña(10, True, True, True, True)
    print("La contraseña generada: ", contraseña)
    print("Se la ha copiada en el portapapeles")
    pyperclip.copy(contraseña)
    print(pyperclip.paste())
    print("y la pegada luego.")

In [237]:
main_crear_contraseña()

La contraseña generada:  EaNoWH!4"#
Se la ha copiada en el portapapeles
EaNoWH!4"#
y la pegada luego.

2. Procesamiento de datos simple

Una compañera de trabajo nos ha pedido un favor, aprovechando que sabe que estamos aprendiendo a programar. Tiene un histórico de partidos de fútbol catalán en un fichero, donde se almacenan los nombres de los equipos y los resultados. Necesita que procesemos los datos de forma automática, para extraer los resultados que necesita.

Utiliza el archivo "historic_partits.txt"

Necesita un programa que devuelva:

- El número total de goles que ha marcado cada equipo.
- El nombre del equipo más goleador.
- El nombre del equipo más goleado
- La clasificación global (cada victoria: 3 pts, empate 1 pts, derrota 0 pts)

Importamos la libreria pandas.

In [20]:
import pandas as pd

Creamos el Dataframe desde el fichero con datos de partidos.

In [21]:
df = pd.read_csv('historic partits.txt', sep='\t', header=None)
print(df.head(10))

              0    1           2
0       Manlleu  0-1  Granollers
1    Vilafranca  4-5    Terrassa
2          Olot  5-0  Granollers
3    Vilafranca  5-5     Manlleu
4      Cornellà  5-1        Prat
5    Cerdanyola  0-5  Vilafranca
6   Sant Andreu  2-3    Cornellà
7    Vilafranca  5-4        Olot
8  FC Barcelona  4-4    Badalona
9    Granollers  1-5    Sabadell

In [22]:
print(f"Tenemos el Dataframe de {df.shape[0]} registros y {df.shape[1]} columnas.")

Tenemos el Dataframe de 500 registros y 3 columnas.

Comprobamos que no hay valores nulos en el Dataframe.

In [23]:
df.isnull().any()

0    False
1    False
2    False
dtype: bool

La lista de equipos locales:

In [24]:
df[0].value_counts().sort_index()

0
Badalona               20
Cerdanyola             26
Cornellà               27
Europa                 18
FC Barcelona           24
Figueres               22
Girona FC              25
Granollers             24
Llagostera             30
Lleida Esportiu        19
Manlleu                21
Nàstic de Tarragona    28
Olot                   30
Prat                   28
RCD Espanyol           24
Reus Deportiu          21
Sabadell               31
Sant Andreu            27
Terrassa               27
Vilafranca             28
Name: count, dtype: int64

La lista de equipos visitantes.

In [25]:
df[2].value_counts().sort_index()

2
Badalona               28
Cerdanyola             24
Cornellà               27
Europa                 15
FC Barcelona           20
Figueres               34
Girona FC              22
Granollers             25
Llagostera             26
Lleida Esportiu        33
Manlleu                22
Nàstic de Tarragona    27
Olot                   24
Prat                   17
RCD Espanyol           31
Reus Deportiu          23
Sabadell               17
Sant Andreu            26
Terrassa               30
Vilafranca             29
Name: count, dtype: int64

Creamos la función que recibe el numero de goles marcados y goles encajados y devuelve en número de puntos que consigue el equipo en el pratido.

In [248]:
def getPuntos(gols1, gols2):
    if gols1 == gols2:
        return 1
    if gols1 > gols2:
        return 3
    else:
        return 0

Agregamos para el equipo local y el visitante las columnas con los numeros de goles marcados y encajados, puntos y cual fue el partido: ganado, perdido o empatado.

In [27]:
df['gols_marcados_1'] = df[1].str[0]
df['gols_encajados_1'] = df[1].str[2]
df['gols_marcados_2'] = df[1].str[2]
df['gols_encajados_2'] = df[1].str[0]
df['puntos_1'] = df.apply( lambda x: getPuntos( x['gols_marcados_1'], x['gols_encajados_1'] ), axis=1 )
df['puntos_2'] = df.apply( lambda x: getPuntos( x['gols_marcados_2'], x['gols_encajados_2'] ), axis=1 )

df['partido_ganado_1'] = 0
df['partido_empatado_1'] = 0
df['partido_perdido_1'] = 0
df.loc[ df['gols_marcados_1'] > df['gols_encajados_1'],  'partido_ganado_1'] = 1
df.loc[ df['gols_marcados_1'] == df['gols_encajados_1'],  'partido_empatado_1'] = 1 
df.loc[ df['gols_marcados_1'] < df['gols_encajados_1'],  'partido_perdido_1'] = 1

df['partido_ganado_2'] = 0
df['partido_empatado_2'] = 0
df['partido_perdido_2'] = 0
df.loc[ df['gols_marcados_2'] > df['gols_encajados_2'],  'partido_ganado_2'] = 1
df.loc[ df['gols_marcados_2'] == df['gols_encajados_2'],  'partido_empatado_2'] = 1 
df.loc[ df['gols_marcados_2'] < df['gols_encajados_2'],  'partido_perdido_2'] = 1


df = df.rename(columns={ 0: 'equipo_1', 2:'equipo_2' })


# Cambiamos los tipos de columnas
df['gols_marcados_1'] = df['gols_marcados_1'].astype('int')
df['gols_encajados_1'] = df['gols_encajados_1'].astype('int')
df['gols_marcados_2'] = df['gols_marcados_2'].astype('int')
df['gols_encajados_2'] = df['gols_encajados_2'].astype('int')
df['puntos_1'] = df['puntos_1'].astype('int')
df['puntos_2'] = df['puntos_2'].astype('int')
df['equipo_1'] = df['equipo_1'].astype("string")
df['equipo_2'] = df['equipo_2'].astype("string")

df.head(5)

,equipo_1,1,equipo_2,gols_marcados_1,gols_encajados_1,gols_marcados_2,gols_encajados_2,puntos_1,puntos_2,partido_ganado_1,partido_empatado_1,partido_perdido_1,partido_ganado_2,partido_empatado_2,partido_perdido_2
0,Manlleu,0-1,Granollers,0,1,1,0,0,3,0,0,1,1,0,0
1,Vilafranca,4-5,Terrassa,4,5,5,4,0,3,0,0,1,1,0,0
2,Olot,5-0,Granollers,5,0,0,5,3,0,1,0,0,0,0,1
3,Vilafranca,5-5,Manlleu,5,5,5,5,1,1,0,1,0,0,1,0
4,Cornellà,5-1,Prat,5,1,1,5,3,0,1,0,0,0,0,1

Creamos el Dataframes separados para los equipos locales y los visitantes para concatenarlos a continuación.

In [28]:
df_equipo1 = df[['equipo_1', 'gols_marcados_1', 'gols_encajados_1', 'puntos_1', 'partido_ganado_1', 'partido_empatado_1', 'partido_perdido_1']]
df_equipo2 = df[['equipo_2', 'gols_marcados_2', 'gols_encajados_2', 'puntos_2', 'partido_ganado_2', 'partido_empatado_2', 'partido_perdido_2']]

df_equipo1 = df_equipo1.rename( columns = {'equipo_1': 'equipo', 'gols_marcados_1':'gols_marcados', \
                                                        'gols_encajados_1': 'gols_encajados', 'puntos_1':'puntos', \
                                                            'partido_ganado_1': 'partido_ganado', 'partido_empatado_1': 'partido_empatado', \
                                                                'partido_perdido_1': 'partido_perdido'} )

df_equipo2 = df_equipo2.rename( columns = {'equipo_2': 'equipo', 'gols_marcados_2':'gols_marcados', \
                                                        'gols_encajados_2': 'gols_encajados', 'puntos_2':'puntos', \
                                                            'partido_ganado_2': 'partido_ganado', 'partido_empatado_2': 'partido_empatado', \
                                                                'partido_perdido_2': 'partido_perdido'} )

El Dataframe con resultado final.

In [29]:
df_result = pd.concat([df_equipo1, df_equipo2], ignore_index=True)
df_result.head(10)

,equipo,gols_marcados,gols_encajados,puntos,partido_ganado,partido_empatado,partido_perdido
0,Manlleu,0,1,0,0,0,1
1,Vilafranca,4,5,0,0,0,1
2,Olot,5,0,3,1,0,0
3,Vilafranca,5,5,1,0,1,0
4,Cornellà,5,1,3,1,0,0
5,Cerdanyola,0,5,0,0,0,1
6,Sant Andreu,2,3,0,0,0,1
7,Vilafranca,5,4,3,1,0,0
8,FC Barcelona,4,4,1,0,1,0
9,Granollers,1,5,0,0,0,1

Agrupamos el Dataframe final por la columna "equipo" sumando los valores de otras columnas y sorteamos por la columna "puntos".

- La clasificación global.

In [30]:
clasificacion = df_result.groupby(['equipo']).sum().sort_values(by="puntos", ascending=False)
clasificacion

,gols_marcados,gols_encajados,puntos,partido_ganado,partido_empatado,partido_perdido
equipo,,,,,,
Girona FC,139,94,96,31,3,13
Llagostera,159,142,94,29,7,20
Sabadell,141,121,85,26,7,15
Cornellà,147,146,82,25,7,22
RCD Espanyol,131,144,80,23,11,21
Figueres,161,154,79,23,10,23
Lleida Esportiu,129,133,75,23,6,23
Terrassa,147,164,74,20,14,23
FC Barcelona,125,115,73,22,7,15
Vilafranca,157,172,72,20,12,25
Reus Deportiu,119,111,68,20,8,16
Badalona,134,124,68,18,14,16
Nàstic de Tarragona,130,148,68,20,8,27
Granollers,122,117,67,21,4,24
Olot,132,144,64,18,10,26
Sant Andreu,123,134,62,17,11,25
Manlleu,106,118,57,16,9,18
Prat,106,111,56,16,8,21
Cerdanyola,117,133,56,17,5,28
Europa,93,93,41,12,5,16

- El nombre del equipo más goleador.

In [31]:
clasificacion.loc[ clasificacion['gols_marcados'] == max(clasificacion['gols_marcados']), ['gols_marcados', 'puntos'] ]

          gols_marcados  puntos
equipo
Figueres            161      79

- El nombre del equipo más goleado.

In [32]:
clasificacion.loc[ clasificacion['gols_encajados'] == max(clasificacion['gols_encajados']), ['gols_encajados', 'puntos'] ]

            gols_encajados  puntos
equipo
Vilafranca             172      72

- El número total de goles que ha marcado cada equipo.

In [33]:
clasificacion['gols_marcados'].sort_values(ascending=False)

equipo
Figueres               161
Llagostera             159
Vilafranca             157
Cornellà               147
Terrassa               147
Sabadell               141
Girona FC              139
Badalona               134
Olot                   132
RCD Espanyol           131
Nàstic de Tarragona    130
Lleida Esportiu        129
FC Barcelona           125
Sant Andreu            123
Granollers             122
Reus Deportiu          119
Cerdanyola             117
Manlleu                106
Prat                   106
Europa                  93
Name: gols_marcados, dtype: int32

He escrito una función para automatizar el procesamiento de datos del fichero.

In [ ]:
def clasificadorDeEquipos(fichero):
    df = pd.read_csv(fichero, sep='\t', header=None)

    df['gols_marcados_1'] = df[1].str[0]
    df['gols_encajados_1'] = df[1].str[2]
    df['gols_marcados_2'] = df[1].str[2]
    df['gols_encajados_2'] = df[1].str[0]
    df['puntos_1'] = df.apply( lambda x: getPuntos( x['gols_marcados_1'], x['gols_encajados_1'] ), axis=1 )
    df['puntos_2'] = df.apply( lambda x: getPuntos( x['gols_marcados_2'], x['gols_encajados_2'] ), axis=1 )

    df['partido_ganado_1'] = 0
    df['partido_empatado_1'] = 0
    df['partido_perdido_1'] = 0
    df.loc[ df['gols_marcados_1'] > df['gols_encajados_1'],  'partido_ganado_1'] = 1
    df.loc[ df['gols_marcados_1'] == df['gols_encajados_1'],  'partido_empatado_1'] = 1 
    df.loc[ df['gols_marcados_1'] < df['gols_encajados_1'],  'partido_perdido_1'] = 1

    df['partido_ganado_2'] = 0 
    df['partido_empatado_2'] = 0
    df['partido_perdido_2'] = 0
    df.loc[ df['gols_marcados_2'] > df['gols_encajados_2'],  'partido_ganado_2'] = 1
    df.loc[ df['gols_marcados_2'] == df['gols_encajados_2'],  'partido_empatado_2'] = 1 
    df.loc[ df['gols_marcados_2'] < df['gols_encajados_2'],  'partido_perdido_2'] = 1


    df = df.rename(columns={ 0: 'equipo_1', 2:'equipo_2' })


    # Cambiamos los tipos de columnas
    df['gols_marcados_1'] = df['gols_marcados_1'].astype('int')
    df['gols_encajados_1'] = df['gols_encajados_1'].astype('int')
    df['gols_marcados_2'] = df['gols_marcados_2'].astype('int')
    df['gols_encajados_2'] = df['gols_encajados_2'].astype('int')
    df['puntos_1'] = df['puntos_1'].astype('int')
    df['puntos_2'] = df['puntos_2'].astype('int')
    df['equipo_1'] = df['equipo_1'].astype("string")
    df['equipo_2'] = df['equipo_2'].astype("string")

    df_equipo1 = df[['equipo_1', 'gols_marcados_1', 'gols_encajados_1', 'puntos_1', 'partido_ganado_1', 'partido_empatado_1', 'partido_perdido_1']]
    df_equipo2 = df[['equipo_2', 'gols_marcados_2', 'gols_encajados_2', 'puntos_2', 'partido_ganado_2', 'partido_empatado_2', 'partido_perdido_2']]

    df_equipo1 = df_equipo1.rename( columns = {'equipo_1': 'equipo', 'gols_marcados_1':'gols_marcados', \
                                                        'gols_encajados_1': 'gols_encajados', 'puntos_1':'puntos', \
                                                            'partido_ganado_1': 'partido_ganado', 'partido_empatado_1': 'partido_empatado', \
                                                                'partido_perdido_1': 'partido_perdido'} )

    df_equipo2 = df_equipo2.rename( columns = {'equipo_2': 'equipo', 'gols_marcados_2':'gols_marcados', \
                                                        'gols_encajados_2': 'gols_encajados', 'puntos_2':'puntos', \
                                                            'partido_ganado_2': 'partido_ganado', 'partido_empatado_2': 'partido_empatado', \
                                                                'partido_perdido_2': 'partido_perdido'} )
    
    df_result = pd.concat([df_equipo1, df_equipo2], ignore_index=True)
    clasificacion = df_result.groupby(['equipo']).sum().sort_values(by="puntos", ascending=False)
    return clasificacion

In [268]:
def main_clasificador_de_equipos():
    file_path = 'historic partits.txt'
    print(clasificadorDeEquipos(file_path))

In [269]:
main_clasificador_de_equipos()

                     gols_marcados  gols_encajados  puntos  partido_ganado  \
equipo
Girona FC                      139              94      96              31
Llagostera                     159             142      94              29
Sabadell                       141             121      85              26
Cornellà                       147             146      82              25
RCD Espanyol                   131             144      80              23
Figueres                       161             154      79              23
Lleida Esportiu                129             133      75              23
Terrassa                       147             164      74              20
FC Barcelona                   125             115      73              22
Vilafranca                     157             172      72              20
Reus Deportiu                  119             111      68              20
Badalona                       134             124      68              18
Nàstic de Tarragona            130             148      68              20
Granollers                     122             117      67              21
Olot                           132             144      64              18
Sant Andreu                    123             134      62              17
Manlleu                        106             118      57              16
Prat                           106             111      56              16
Cerdanyola                     117             133      56              17
Europa                          93              93      41              12

                     partido_empatado  partido_perdido
equipo
Girona FC                           3               13
Llagostera                          7               20
Sabadell                            7               15
Cornellà                            7               22
RCD Espanyol                       11               21
Figueres                           10               23
Lleida Esportiu                     6               23
Terrassa                           14               23
FC Barcelona                        7               15
Vilafranca                         12               25
Reus Deportiu                       8               16
Badalona                           14               16
Nàstic de Tarragona                 8               27
Granollers                          4               24
Olot                               10               26
Sant Andreu                        11               25
Manlleu                             9               18
Prat                                8               21
Cerdanyola                          5               28
Europa                              5               16