In [194]:
import pandas as pd

In [195]:
df_orden = pd.read_csv('../Dataset/archivo.csv')

## Revisión de datos y resolución de problemas de tipificación

#### Dataframe **df_orden** con datos detallados sobre el historal de fallas de maquinas de costura.

#### Estos datos se registran manualmente en Órdenes de Trabajo (WO)

In [196]:
df_orden.head(5)

,equipment,operation,wo_type,base_model,problem_code,problem_desc,failure_code,failure_desc,cause_code,cause_desc,...,action_desc,mechanic,date,downtime_gross,pit_coverage,real_downtime,parts_cost,repair_hours,waiting_hours,changed_pcs
0,100268,BIND LEG,Calibration,VF2500,SEWP001,It does not sew / No cose,SEWF001,Machine head failure stopping sewing / Falla ...,SEWC001,Misadjusted machine head needle guard / Guarda...,...,Adjust machine head needle guard / Ajustar gua...,Erick Garcia Lima,7/14/2023,0.083333,0.08,0.003333,$0.74,0.083333,0.0,0
1,100268,BIND LEG,Corrective Maintenance,VF2500,SEWP002,It sews with defect / Cose con defecto,SEWF001,Machine head failure stopping sewing / Falla ...,SEWC017,Misadjusted machine head teeth / Dientes de ca...,...,Adjust machine head teeth / Ajustar dientes de...,Jaime Rivera,10/3/2023,1.250000,0.00,1.250000,$16.81,1.250000,0.0,1
2,100268,BIND LEG,Corrective Maintenance,VF2500,SEWP002,It sews with defect / Cose con defecto,SEWF001,Machine head failure stopping sewing / Falla ...,SEWC017,Misadjusted machine head teeth / Dientes de ca...,...,Adjust machine head teeth / Ajustar dientes de...,Jaime Rivera,10/3/2023,1.250000,0.00,1.250000,$16.81,1.250000,0.0,1
3,100268,BIND LEG,Corrective Maintenance,VF2500,SEWP002,It sews with defect / Cose con defecto,SEWF001,Machine head failure stopping sewing / Falla ...,SEWC012,Misadjusted machine head needle bar / Barra de...,...,Adjust machine head teeth / Ajustar dientes de...,Jaime Rivera,1/17/2024,3.000000,3.00,0.000000,$12.50,2.000000,1.0,2
4,100312,BARTACK,Corrective Maintenance,LT2-B872,SEWP001,It does not sew / No cose,SEWF001,Machine head failure stopping sewing / Falla ...,SEWC005,Broken machine head ball joint / Rotura de bie...,...,Replace machine head ball joint / Reemplazar b...,JERONIMO FUNEZ,3/18/2023,0.250000,0.00,0.250000,$2.67,0.250000,0.0,0

In [197]:
print(f'Dataset cuenta {df_orden.shape[0]} registros y {df_orden.shape[1]} variables.')

Dataset cuenta 149066 registros y 21 variables.

In [198]:
df_orden.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149066 entries, 0 to 149065
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   equipment       149066 non-null  int64
 1   operation       149066 non-null  object
 2   wo_type         149066 non-null  object
 3   base_model      149066 non-null  object
 4   problem_code    149066 non-null  object
 5   problem_desc    149066 non-null  object
 6   failure_code    149066 non-null  object
 7   failure_desc    149066 non-null  object
 8   cause_code      149066 non-null  object
 9   cause_desc      149066 non-null  object
 10  action_code     149066 non-null  object
 11  action_desc     149066 non-null  object
 12  mechanic        149066 non-null  object
 13  date            149066 non-null  object
 14  downtime_gross  149066 non-null  float64
 15  pit_coverage    149066 non-null  float64
 16  real_downtime   149066 non-null  float64
 17  parts_cost      149066 non-null  object
 18  repair_hours    149066 non-null  float64
 19  waiting_hours   149066 non-null  float64
 20  changed_pcs     149066 non-null  int64
dtypes: float64(5), int64(2), object(14)
memory usage: 23.9+ MB

#### Lista de variables con el número de valores únicos y ejemplos de valores.

In [199]:
variables = pd.DataFrame(columns=['Variable', 'Número de valores unicos', 'Valores'])
for i, var in enumerate(df_orden.columns):
    variables.loc[i] = [var, df_orden[var].nunique(), df_orden[var].unique().tolist()]

variables

,Variable,Número de valores unicos,Valores
0,equipment,7404,"[100268, 100312, 100452, 100884, 101632, 10163..."
1,operation,59,"[BIND LEG, BARTACK, SET SLEEVE, TOP STITCH, SE..."
2,wo_type,7,"[Calibration, Corrective Maintenance, Breakdow..."
3,base_model,123,"[VF2500, LT2-B872, AZ8403, W664, EX5214, VG270..."
4,problem_code,24,"[SEWP001, SEWP002, SEWP005, SEWP011, SEWP009, ..."
5,problem_desc,24,"[It does not sew / No cose, It sews with defec..."
6,failure_code,38,"[SEWF001, SEWF009, SEWF018, SEWF002, SEWF028, ..."
7,failure_desc,38,[Machine head failure stopping sewing / Falla...
8,cause_code,280,"[SEWC001, SEWC017, SEWC012, SEWC005, SEWC091, ..."
9,cause_desc,280,[Misadjusted machine head needle guard / Guard...
10,action_code,279,"[SEWA001, SEWA013, SEWA005, SEWA003, SEWA094, ..."
11,action_desc,279,[Adjust machine head needle guard / Ajustar gu...
12,mechanic,186,"[Erick Garcia Lima, Jaime Rivera, JERONIMO FUN..."
13,date,501,"[7/14/2023, 10/3/2023, 1/17/2024, 3/18/2023, 1..."
14,downtime_gross,389,"[0.083333333, 1.25, 3.0, 0.25, 2.0, 0.5, 0.2, ..."
15,pit_coverage,371,"[0.08, 0.0, 3.0, 0.25, 0.5, 0.83, 1.42, 0.92, ..."
16,real_downtime,564,"[0.003333333, 1.25, 0.0, 0.25, 2.0, 0.5, 0.2, ..."
17,parts_cost,6545,"[$0.74 , $16.81 , $12.50 , $2.67 , $4.00 , $28..."
18,repair_hours,276,"[0.083333333, 1.25, 2.0, 0.25, 0.5, 0.2, 0.333..."
19,waiting_hours,329,"[0.0, 1.0, 0.083333333, 0.016666667, 0.1666666..."
20,changed_pcs,16,"[0, 1, 2, 3, 7, 9, 10, 4, 8, 6, 5, 12, 11, 14,..."

#### Revisión de valores nulos.

Se ve que dataframe no tiene valores nulos.

In [200]:
# Valores nulos por variable
nulos_df_orden = df_orden.isnull().sum()

# Calcular el porcentaje de nulos
nulos_df_orden = (nulos_df_orden / len(df_orden)) * 100

null_info = pd.DataFrame({
    'Variable': nulos_df_orden.index,
    'Nulos': nulos_df_orden.values,
    'Porcentaje de Nulos': nulos_df_orden.values
})

null_info

          Variable  Nulos  Porcentaje de Nulos
0        equipment    0.0                  0.0
1        operation    0.0                  0.0
2          wo_type    0.0                  0.0
3       base_model    0.0                  0.0
4     problem_code    0.0                  0.0
5     problem_desc    0.0                  0.0
6     failure_code    0.0                  0.0
7     failure_desc    0.0                  0.0
8       cause_code    0.0                  0.0
9       cause_desc    0.0                  0.0
10     action_code    0.0                  0.0
11     action_desc    0.0                  0.0
12        mechanic    0.0                  0.0
13            date    0.0                  0.0
14  downtime_gross    0.0                  0.0
15    pit_coverage    0.0                  0.0
16   real_downtime    0.0                  0.0
17      parts_cost    0.0                  0.0
18    repair_hours    0.0                  0.0
19   waiting_hours    0.0                  0.0
20     changed_pcs    0.0                  0.0

#### Variables **problem_code, failure_code, cause_code, action_code** duplican la informacion de las columnas **problem_desc, failure_desc, cause_desc, action_desc** respectivamente. 
#### Para facilitar la interpretación quedamos con columnas descriptivas.

In [201]:
df_orden.drop(columns=['problem_code', 'failure_code', 'cause_code', 'action_code'], inplace=True)

#### Python ha tipificado las variables **problem_desc, failure_desc, cause_desc, action_desc** como object.

#### Cambiamos el tipo de variables por category.

In [202]:
df_orden[['problem_desc', 'failure_desc', 'cause_desc', 'action_desc']] = \
    df_orden[['problem_desc', 'failure_desc', 'cause_desc', 'action_desc']].astype('category')

#### Variables **operation, wo_type, base_model, mechanic** son también categóricas.

In [203]:
df_orden[['operation', 'wo_type', 'base_model', 'mechanic']] = \
    df_orden[['operation', 'wo_type', 'base_model', 'mechanic']].astype('category')

#### Variable **parts_cost**.

Eliminamos símbolos de **$** , paréntesis de apertura y de cirre y comas y convertimos a float.

In [204]:
', '.join(df_orden['parts_cost'].head(20).astype(str))

'$0.74 , $16.81 , $16.81 , $12.50 , $2.67 , $2.67 , $4.00 , $4.00 , $28.50 , $28.50 , $25.18 , $25.18 , $0.00 , $0.00 , $0.00 , $0.00 , $0.00 , $0.00 , $1.50 , $0.76 '

In [205]:
df_orden['parts_cost'] = df_orden['parts_cost'].str.replace('$', '').str.replace(',', '').str.replace('(', '').str.replace(')', '').astype(float)

In [206]:
', '.join(df_orden['parts_cost'].head(20).astype(str))

'0.74, 16.81, 16.81, 12.5, 2.67, 2.67, 4.0, 4.0, 28.5, 28.5, 25.18, 25.18, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.5, 0.76'

#### Variable **date**.

In [207]:
df_orden['date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 149066 entries, 0 to 149065
Series name: date
Non-Null Count   Dtype
--------------   -----
149066 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB

In [208]:
', '.join(df_orden['date'].head(20).astype(str))

'7/14/2023, 10/3/2023, 10/3/2023, 1/17/2024, 3/18/2023, 3/18/2023, 11/11/2023, 11/11/2023, 7/2/2023, 7/2/2023, 7/19/2023, 7/19/2023, 10/7/2023, 10/7/2023, 11/8/2023, 11/8/2023, 11/8/2023, 11/8/2023, 2/26/2024, 3/6/2024'

Convertimos los valores de la **date** a datetime.

In [209]:
df_orden['date'] = pd.to_datetime(df_orden['date'])
df_orden['date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 149066 entries, 0 to 149065
Series name: date
Non-Null Count   Dtype
--------------   -----
149066 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.1 MB

In [210]:
', '.join(df_orden['date'].head(20).astype(str))

'2023-07-14, 2023-10-03, 2023-10-03, 2024-01-17, 2023-03-18, 2023-03-18, 2023-11-11, 2023-11-11, 2023-07-02, 2023-07-02, 2023-07-19, 2023-07-19, 2023-10-07, 2023-10-07, 2023-11-08, 2023-11-08, 2023-11-08, 2023-11-08, 2024-02-26, 2024-03-06'

#### Variable **downtime_gross**.

Observamos que hay valores negativos de la **downtime_gross**.

In [211]:
df_orden['downtime_gross'][df_orden['downtime_gross'] < 0]

37912    -2.800000
37913    -2.800000
103184   -6.383333
107718   -0.100000
Name: downtime_gross, dtype: float64

Eliminamos registros con valores negativas.

In [212]:
df_orden = df_orden.drop(index = df_orden['downtime_gross'][df_orden['downtime_gross'] < 0].index)

#### Variable **waiting_hours**.

Observamos que hay valores negativos de la **waiting_hours**.

In [213]:
df_orden['waiting_hours'][df_orden['waiting_hours'] < 0]

847      -1.666667
1595     -0.816667
5494     -0.333333
5521     -0.750000
5522     -0.750000
            ...
135176   -0.400000
141416   -2.000000
141417   -2.000000
141463   -0.333333
143664   -0.166667
Name: waiting_hours, Length: 85, dtype: float64

Eliminamos registros con valores negativas.

In [214]:
df_orden = df_orden.drop(index = df_orden['waiting_hours'][df_orden['waiting_hours'] < 0].index)

#### Variable **mechanic**

In [215]:
filtro1 = df_orden['mechanic'] == 'GALEAS PEREZ EDWIN ROGELIO'
filtro2 = df_orden['mechanic'] == 'Edwin Rogelio Galeas Perez'

In [216]:
df_orden['mechanic'][filtro1 | filtro2 ]

8954      Edwin Rogelio Galeas Perez
8955      Edwin Rogelio Galeas Perez
8956      Edwin Rogelio Galeas Perez
8957      Edwin Rogelio Galeas Perez
9048      GALEAS PEREZ EDWIN ROGELIO
                     ...
131163    GALEAS PEREZ EDWIN ROGELIO
131194    GALEAS PEREZ EDWIN ROGELIO
131195    GALEAS PEREZ EDWIN ROGELIO
131196    GALEAS PEREZ EDWIN ROGELIO
131226    GALEAS PEREZ EDWIN ROGELIO
Name: mechanic, Length: 1755, dtype: category
Categories (186, object): [' Pedro Miguel Martinez Linares', 'ALLAN RIVERA', 'ANGEL MATAMOROS', 'Abel Alberto Ramirez Rivera', ..., 'William Alexander Arevalo Leiva', 'Willian Tejada', 'Wilmer Zamora', 'Xavier Jose Mendoza']

Cambiamos el nombre de mecánico porque está escrito en dos formas.

In [217]:
df_orden['mechanic'][filtro1] = 'Edwin Rogelio Galeas Perez'

#### Agregamos la variable **days_between_failures**.

In [218]:
df_orden = df_orden.sort_values(["equipment","date"])

In [219]:
df_orden['days_between_failures'] = df_orden.groupby("equipment")["date"].diff().dt.days

In [220]:
df_orden['days_between_failures'].isnull().sum()

7404

In [221]:
df_orden = df_orden.dropna(subset=['days_between_failures']).reset_index()

if 'index' in df_orden.columns:
    df_orden.drop(columns='index', inplace=True)

# df_orden['days_between_failures'] = df_orden['days_between_failures'].fillna( (df_orden['date'] - pd.Timestamp('2023-01-01') ).dt.days )
# df_orden['days_between_failures'] = df_orden['days_between_failures'].astype(int)

#### Al final tenemos el dataset limpiado.

In [222]:
print(f'Dataset tiene {df_orden.shape[0]} registros y {df_orden.shape[1]} variables.\n')
df_orden.info()

Dataset tiene 141573 registros y 18 variables.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141573 entries, 0 to 141572
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   equipment              141573 non-null  int64
 1   operation              141573 non-null  category
 2   wo_type                141573 non-null  category
 3   base_model             141573 non-null  category
 4   problem_desc           141573 non-null  category
 5   failure_desc           141573 non-null  category
 6   cause_desc             141573 non-null  category
 7   action_desc            141573 non-null  category
 8   mechanic               141573 non-null  category
 9   date                   141573 non-null  datetime64[ns]
 10  downtime_gross         141573 non-null  float64
 11  pit_coverage           141573 non-null  float64
 12  real_downtime          141573 non-null  float64
 13  parts_cost             141573 non-null  float64
 14  repair_hours           141573 non-null  float64
 15  waiting_hours          141573 non-null  float64
 16  changed_pcs            141573 non-null  int64
 17  days_between_failures  141573 non-null  float64
dtypes: category(8), datetime64[ns](1), float64(7), int64(2)
memory usage: 12.3 MB

In [223]:
df_orden.to_parquet('../Dataset limpiado/ordenes_de_trabajo.parquet')